SELECT *FROM Customer
SELECT *FROM prod_cat_info
SELECT *FROM Transactions

--DATA PREPARATION AND UNDERSTANDING 

--1) What is the total number of rows in each of the 3tables in the database ?
SELECT COUNT(*) AS TOTAL_ROWS
FROM Customer;

--2)  WHAT IS THE TOTAL NO OF TRANSACTIONS THAT HAVE A RETURN ?
ANS:- SELECT COUNT(*) AS TOTAL_RETURNED_TRANSACTIONS
FROM Transactions
WHERE total_amt =1;

--3) As you would have noticed, the dates provided across the datasets are not in a correct format.
--As first steps, pls convert the date variables into valid date formats before proceeding ahead.
SELECT CONVERT(DATE,tran_date,101) AS formatted_date
FROM Transactions;

--4)  What is the time range of the transaction data available for analysis? Show the output in number of days, months and years simultaneously in different columns.
SELECT DATEDIFF(DAY,'2014-02-28',GETDATE()) AS
DIFFERENCEIN_DAYS,DATEDIFF(MONTH,'2014-02-28',GETDATE()) AS
DIFFERENCEIN_MONTHS,DATEDIFF(YEAR,'2014-02-28',GETDATE()) AS DIFFERENCEIN_YEARS

--5) Which product category does the sub-category “DIY” belong to?
SELECT prod_cat, prod_subcat
FROM prod_cat_info
WHERE prod_subcat = 'DIY'

--DATA ANALYSIS

--1) Which channel is most frequently used for transactions? 

SELECT TOP 1 store_type,COUNT(store_type) COUNT_CHANNEL_TYPE
FROM transactions
GROUP BY Store_type
ORDER BY COUNT(Store_type) DESC

--2) What is the count of Male and Female customers in the database?

SELECT GENDER, COUNT(GENDER) AS COUNT_GENDERS
FROM Customer
WHERE GENDER IS NOT NULL
GROUP BY GENDER

--3) From which city do we have the maximum number of customers and how many?

SELECT TOP 1 CITY_CODE, COUNT(CUSTOMER_ID) AS MAX_CUSTOMERS
FROM Customer
GROUP BY CITY_CODE
ORDER BY COUNT(CUSTOMER_ID) DESC

--4) How many sub-categories are there under the Books category?

SELECT prod_cat, COUNT(prod_subcat) AS COUNT_SUB_CATEGORIES
FROM prod_cat_info
WHERE prod_cat ='books'
GROUP BY prod_cat

--5)  What is the maximum quantity of products ever ordered?

SELECT TOP 1
Qty AS [MAXIMUM PRODUCT SOLD] from transactions
WHERE Qty > 0
ORDER BY Qty DESC

--6)  What is the net total revenue generated in categories Electronics and Books?

SELECT B.prod_cat,
SUM(CAST(A.total_amt AS FLOAT)) AS net_revenue from Transactions AS A
INNER JOIN prod_cat_info AS B ON 
A.prod_cat_code=B.prod_cat_code
WHERE B.prod_cat
IN('electronics','Books')
GROUP BY B.prod_cat

--7)  How many customers have >10 transactions with us, excluding returns?

SELECT COUNT(transaction_id) COUNT_transactions, Cust_id AS Customer_id
FROM Transactions
WHERE Qty > 0
GROUP BY Cust_id
HAVING COUNT(Transaction_id) > 10

--8)  What is the combined revenue earned from the “Electronics” & “Clothing” categories, from “Flagship stores”?

SELECT ROUND((SUM(CONVERT(FLOAT, total_amt))),2) AS REVENUE,prod_cat, store_type
FROM
(SELECT total_amt, prod_cat, store_type FROM prod_cat_info A
INNER JOIN Transactions B ON A.prod_cat_code = B.prod_cat_code AND
A.prod_sub_cat_code = B. prod_subcat_code) AS T1
WHERE prod_cat IN('electronics','clothing') AND store_type = 'Flagship store' AND
CONVERT(FLOAT, total_amt) > 0
GROUP BY prod_cat, store_type

--9)  What is the total revenue generated from “Male” customers in “Electronics” category? Output should display total revenue by prod sub-cat.

SELECT ROUND((SUM(CONVERT(FLOAT,total_amt))),2) AS  revenue, gender, prod_cat,
prod_subcat
FROM
(SELECT total_amt, gender, prod_cat, prod_subcat FROM Customer AS A
FULL JOIN Transactions AS B ON A.Customer_id = B.cust_id
FULL JOIN prod_cat_info AS C ON B.prod_cat_code = C.prod_cat_code AND 
B.prod_subcat_code = C.prod_sub_cat_code) AS T1
WHERE GENDER = 'M' AND prod_cat = 'electronics' AND  CONVERT(FLOAT, total_amt) > 0
GROUP BY GENDER, prod_cat, prod_subcat

--10)  What is percentage of sales and returns by product sub category; display only top 5 sub categories in terms of sales?

SELECT TOP 5 
ROUND(SUM(CAST(total_amt AS float)),2) AS total_sales,
P.prod_subcat
FROM Transactions AS T
INNER JOIN prod_cat_info AS P
ON T.prod_subcat_code = P.prod_sub_cat_code
WHERE T.Qty > 0
GROUP BY P.prod_subcat
ORDER BY total_sales DESC

--11)  For all customers aged between 25 to 35 years find what is the net total revenue generated by 
--these consumers in last 30 days of transactions from max transaction date available in the data?

SELECT DATEDIFF(YEAR,CONVERT(DATE,DOB,103),GETDATE()) AS AGE,
ROUND(SUM(CONVERT(FLOAT, total_amt)),2) AS total_revenue
FROM
(SELECT DOB,total_amt FROM Customer A INNER JOIN
Transactions B ON A.customer_Id = B.cust_id) AS T1
WHERE CONVERT(FLOAT,total_amt) > 0 AND
DATEDIFF(YEAR,CONVERT(DATE,DOB,103),GETDATE()) BETWEEN 25 AND 35 AND CONVERT(FLOAT,total_amt) > 0
GROUP BY DATEDIFF(YEAR,CONVERT(DATE,DOB,103), GETDATE())

--12) Which product category has seen the max value of returns in the last 3 months of transactions?

WITH A AS
(
SELECT B.prod_cat, A.total_amt,CONVERT(DATE,A.tran_date,103) AS TRAN_DATE FROM Transactions AS A
LEFT JOIN prod_cat_info AS B 
ON A.prod_cat_code = B.prod_cat_code AND A.prod_subcat_code=B.prod_sub_cat_code
--GROUP BY B.prod_cat,A.total_amt,A.tran_date
)
SELECT* FROM A
WHERE A.TRAN_DATE >= (SELECT DATEADD(MONTH,-3,MAX(CONVERT(DATE,B.tran_date,103)))
FROM Transactions AS B)

SELECT *FROM transactions

--13) Which store-type sells the maximum products; by value of sales amount and by quantity sold?

SELECT A.store_type, SUM(A.total_amt) AS sales_amt, SUM(Qty) AS Quantity_sold
FROM Transactions AS A
WHERE A.Store_type IN (
SELECT TOP 1 A.Store_type
FROM Transactions AS A
GROUP BY A.Store_type
ORDER BY SUM(A.Qty)DESC
)
GROUP BY A.Store_type


SELECT store_type,
SUM(total_amt) AS Total_total_amt,
SUM(Qty) AS Total_Qty
FROM Transactions
GROUP BY store_type
SELECT
store_type,
MAX(total_amt) AS max_total_amt,
MAX(Qty) AS max_Qty
FROM Transactions
GROUP BY store_type

--14) What are the categories for which average revenue is above the overall average ?

SELECT P.prod_cat, AVG(t.total_amt) AS average
FROM (SELECT T.*, AVG(t.total_amt) OVER () AS overall_average
FROM Transactions T)
t JOIN
prod_cat_info P
ON T.prod_cat_code =P.prod_cat_code
GROUP BY P.prod_cat, overall_average
HAVING AVG(t.total_amt) > overall_average


--15)  Find the average and total revenue by each subcategory for the categories which are among top 5 categories in terms of quantity sold ?

SELECT p.prod_subcat AS product_subcategory,
AVG(CAST(total_amt AS float)) AS Average_revenue,
SUM(CAST(total_amt AS float)) AS total_revenue
FROM Transactions AS T
INNER JOIN prod_cat_info AS P
ON T.prod_cat_code = P.prod_cat_code AND T.prod_subcat_code = P.prod_sub_cat_code
GROUP BY P.prod_subcat


